server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/